easydigitaldownloads/library

admin/add-username-to-customer-details.php

Adds the customer’s username to the "Customer Details" section on the payment screen, and links it through to the user’s profile

Add Username To Customer Details

---

admin/replace-menu-icon.php

Replace the standard menu icon in Easy Digital Downloads with an icon from Dashicons

Replace Menu Icon

---

downloads/show-featured-image-with-purchase-link.php

Shows a download's featured image with the purchase link

Show Featured Image With Purchase Link

---

emails/milestone-sales-alert.php

Emails the admin when a specific download has been sold X times.

Milestone Sales Alert

---

admin/download-archive-menu-item.php

Add download archive link as page menu item

---

emails/pre-approval-emails.php

Email the admin and customer when a pre-approval payment has been made.

Pre-approval Emails

---

README.md

Shows a logged in customer how much they’ve spent, anywhere on your website.

Update readme with instructions on using snippets

---

admin/download-archive-menu-item.php
admin/download-column-thumbnail.php

Insert a new post column featuring the download thumbnail

---

admin/download-column-thumbnail.php

Sorry for the quickly required patch.

Additionally load css on post type only

---

extensions/gateway-fees/easy-digital-downloads-conditional-gateway-fees.php

Do not charge gateway fee onto customer if amount is over X - Integrates
with gateway fees plugin from easy digital downloads.

Conditional Gateway Fee Add on for Gateway Fees Plugin

---

emails/customize-user-verification-email.php

Adds a snippet for customizing the user verification email.

Customize user verification email.

---

extensions/recurring-payments/sub-payments-in-api.php

Added 'publish' to the array of search criteria, and added a priority of 100 to the add action call

Changes to make it work with my setup

---

extensions/software-licensing/content-restriction-compatibility.php

Make the edd_restrict shortcode check if a license is expired before displaying content.

Make [edd_restrict] check if License Expired

---

admin/force-minimum-password-length-profile-editor.php

Goes along with https://github.com/easydigitaldownloads/library/blob/master/checkout/force-minimum-password-length.php

Verify password minimum length in the EDD profile editor.

---

shortcodes/download_count_shortcode.php
shortcodes/edd_download_count_with_offset_shortcode.php

Download Count with Offset

---

misc/convert-customers-to-users.php

I went ahead and built this from scratch. It's terribly slow, but I wanted to stick to using the `EDD_Customers` and `EDD_Payments` apis.

Add tool to convert customers into users

---

extensions/software-licensing/grandfather-renewal-rate.php

$discount returned null on line 14, this fixes it

Fix variable names

---

admin/restrict-dashboard-summary-widget.php
checkout/checkout-cart-thumbnail-size.php
downloads/additional-purchase-button-add-to-cart-link.php
downloads/display-purchase-button-on-download-archives.php
downloads/download-category-tag-count.php
extensions/auto-register/change-login-link.php
extensions/frontend-submissions/add-vendor-dashboard-tab.php
extensions/frontend-submissions/login-form-redirect.php
extensions/frontend-submissions/registration-form-redirect.php
extensions/social-login/move-checkout-login-buttons-above-gateway-picker.php
extensions/software-licensing/modify-license-key-structure.php
extensions/wallet/add-deposit-levels.php
themes/vendd/display-downloads-purchase-button.css

Sean's accumulated gists

---

.gitignore
checkout/paypal-standard-custom-ipn-url.php

Add function which customizes the PP notify_url

---

misc/ignore-x_accel_redirect.php

Add plugin which ignores X-Accel-Redirect Header

---

extensions/all-access/only-count-last-file.php

Only count the last file in All Access

---

extensions/all-access/weighted-download-count.php

All Access Weighted Downloads

---

extensions/all-access/expire-pass-when-counter-used-up.php

Snippet: Expire AA pass when counter used up

---

extensions/all-access/hide-file-specific-options.php

Add file-specific download options filter

---

_extensions/recurring-payments/one-subscription.html

Fix deprecated notices in recurring methods

---

_extensions/all-access/expire-pass-when-counter-used-up.html

Change title to "Expire pass when counter used up"

---

_downloads/enable-REST.html

Add snippet for supporting downloads in the WP REST API #138

---

_checkout/prevent-duplicate-cart-items.html

Fix typo in prevent duplicate cart items title

---

_extensions/software-licensing/disable-renewal-for-product.html

Add snippet to disable renewals for a specific download #150

---

_extensions/auto-register/change-login-link.html

Updated to match the variable names of the filter.
Updated to use wp_login_url() in the replace functionality to make sure you are changing the correct URL

Small code update and variable changes

---

_misc/change-registration-email-login-url.html

Add 'Change Registration Login URL' snippet #155

---

_extensions/software-licensing/variable-price-expirations.html

Add new filters to support upgrades between variable prices #159
